# 服务
server:
  # 服务端口
  port: 8080

# Spring
spring:
  # 数据源
  datasource:
    # 驱动
     driver-class-name: com.mysql.cj.jdbc.Driver
    # 地址
     url: jdbc:mysql://mysql:3306/blog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    # 用户名
     username: root
    # 密码
     password: baby7blog
  # redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 1000


# mybatis-plus
mybatis-plus:
  # mapper的xml文件位置
  mapper-locations: classpath:/mapper/*.xml
  # 全局策略配置
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
#    # 数据库相关
#    db-config:
#      # 是否开启大写命名
#      capital-mode: true
    db-config:
      id-type: auto
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 为驱动程序设置一个提示，以控制返回结果的获取大小,此参数值可以由查询设置覆盖
    default-fetch-size: 500

logging:
  level:
    com.baby7blog.modules.blog.mapper: trace

# 项目相关配置
file-service:
  # 文件路径
  profile: /root/baby7blog/file/